name: Deploy to AWS Production

on:
  push:
    branches:
      - main  # Robot hanya bekerja kalau ada push ke branch 'main'

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Deploy to Server via SSH
      uses: appleboy/ssh-action@master # Ini robot peminjam tangan kita
      with:
        host: ${{ secrets.HOST_DNS }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.EC2_SSH_KEY }}
        port: 22
        script: |
          echo "ðŸ¤– Robot: Memulai proses deployment..."
          
          # 1. Masuk ke folder project
          cd ~/my-scheduler-project
          
          # 2. Tarik kodingan terbaru
          git pull origin main

          # [BARU] 3. Buat file credentials.json dari GitHub Secrets
          # Robot menulis isi rahasia ke dalam file di server
          echo '${{ secrets.GDRIVE_CREDENTIALS }}' > backup_service/credentials.json
          
          # 4. Matikan & Nyalakan Docker
          echo "ðŸ¤– Robot: Restarting Docker Containers..."
          sudo docker compose up -d --build --remove-orphans
          
          # 5. Bersihkan sampah
          sudo docker image prune -f
          
          echo "âœ… Robot: Deployment Selesai!"